name: Trigger auto deployment for recipegenerator-frontend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
      - '**'
      - '.github/workflows/recipegenerator-frontend-AutoDeployTrigger-5b175a8d-cfb5-4261-aea9-31a53797321f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RECIPEGENERATORFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RECIPEGENERATORFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RECIPEGENERATORFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to Docker Hub
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.RECIPEGENERATORFRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RECIPEGENERATORFRONTEND_REGISTRY_PASSWORD }}
          containerAppName: recipegenerator-frontend
          resourceGroup: saprone-resource-group
          imageToBuild: saprone/recipegenerator-frontend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


